from environs import Env

env = Env()
env.read_env()


class Config:
    RABBITMQ_URI = env("RABBITMQ_URI")
    BOARDS_TO_RENDER_QUEUE = env("BOARDS_TO_RENDER_QUEUE")
    MESSAGES_EXCHANGE = env("MESSAGES_EXCHANGE")
    RENDERED_BOARDS_EXCHANGE = env("RENDERED_BOARDS_EXCHANGE")
    LOGGER_FORMAT_DEBUG = env("LOGGER_FORMAT_DEBUG", None)
    LOGGER_FORMAT_INFO = env("LOGGER_FORMAT_INFO", None)
